INSERT INTO book (book_title, book_author, book_price, book_stock, book_image, book_description)
VALUES
    ('To Kill a Mockingbird', 'Harper Lee', 10.99, 50, 'to_kill_a_mockingbird.jpg', 'A Pulitzer Prize-winning novel set in the American South during the 1930s, exploring themes of racial injustice and moral growth through the eyes of young Scout Finch.'),
    ('1984', 'George Orwell', 12.99, 40, '1984.jpg', 'A dystopian novel depicting a totalitarian regime, surveillance, and the struggle for individual freedom in a bleak future society.'),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 9.99, 60, 'the_great_gatsby.jpg', 'A classic American novel set in the Roaring Twenties, exploring themes of love, wealth, and the American Dream through the eyes of Jay Gatsby and narrator Nick Carraway.'),
    ('Pride and Prejudice', 'Jane Austen', 8.99, 70, 'pride_and_prejudice.jpg', 'A beloved romantic novel set in early 19th-century England, focusing on the complex relationships and societal expectations faced by the Bennet sisters, particularly Elizabeth and Mr. Darcy.'),
    ('Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 14.99, 30, 'harry_potter_and_the_philosophers_stone.jpg', 'The first book in the Harry Potter series, following the adventures of young wizard Harry Potter as he discovers his magical heritage and battles the dark wizard Voldemort.'),
    ('To the Lighthouse', 'Virginia Woolf', 11.99, 45, 'to_the_lighthouse.jpg', 'A pioneering novel of modernist literature, exploring themes of perception, memory, and the passage of time as a family and their guests spend a summer on the Isle of Skye.'),
    ('The Catcher in the Rye', 'J.D. Salinger', 10.49, 55, 'the_catcher_in_the_rye.jpg', 'A coming-of-age novel following Holden Caulfield, a disenchanted teenager navigating the challenges of adolescence, identity, and society in post-World War II America.'),
    ('The Hobbit', 'J.R.R. Tolkien', 13.49, 25, 'the_hobbit.jpg', 'A fantasy novel introducing readers to the world of Middle-earth and the adventures of hobbit Bilbo Baggins as he embarks on a quest to reclaim treasure guarded by the dragon Smaug.'),
    ('The Lord of the Rings', 'J.R.R. Tolkien', 24.99, 20, 'the_lord_of_the_rings.jpg', 'An epic high fantasy trilogy following the journey of the hobbit Frodo Baggins to destroy the One Ring and defeat the Dark Lord Sauron, set in the richly detailed world of Middle-earth.'),
    ('The Chronicles of Narnia', 'C.S. Lewis', 19.99, 35, 'the_chronicles_of_narnia.jpg', 'A series of seven fantasy novels set in the magical land of Narnia, depicting the adventures of children who discover portals to this enchanted realm and encounter its inhabitants, including the noble lion Aslan.')
;
