_security_logout:
    resource: security.route_loader.logout
    type: service

# access_control:
#  - { path: ^/admin, roles: ROLE_ADMIN }
#  - { path: ^/, roles: ROLE_USER}



# role_hierarchy:
#     ROLE_USER : ROLE_USER
#     ROLE_ADMIN : ROLE_ADMIN
